image: ntxcode/docker-gitlab-dind-frontend:node-0.10
stages:
    - build

build:
    stage: build
    script:
        - "[[ -d /cache/zup-web-angular ]] || (mkdir -p /cache/zup-web-angular/node_modules && mkdir /cache/zup-web-angular/bower_components)"
        - ln -s /cache/zup-web-angular/node_modules ./node_modules
        - ln -s /cache/zup-web-angular/bower_components ./app/bower_components
        - npm install && bower install --allow-root
        - touch .env
        - NODE_ENV=production grunt build
        - git config --global user.name 'Gitlab CI'
        - git config --global user.email 'tecnologia@ntdev.com.br'
        - rm -rf zup-web || true
        - git clone --depth 1 --branch $CI_BUILD_REF_NAME https://$DOCKER_USERNAME:$DOCKER_PASSWORD@gitlab.com/ntxcode/zup-web.git || git clone --depth 1 --branch master https://$DOCKER_USERNAME:$DOCKER_PASSWORD@gitlab.com/ntxcode/zup-web.git
        - cd zup-web
        - "[[ $(git symbolic-ref --short -q HEAD) = $CI_BUILD_REF_NAME ]] || git checkout -b $CI_BUILD_REF_NAME"
        - rm -rf zup-web-angular
        - cp -R ../dist ./zup-web-angular
        - git add --all zup-web-angular
        - git commit -m "Build $CI_BUILD_ID"
        - git push origin $CI_BUILD_REF_NAME